### ISSUE TITLE
Code doesn't terminate & Environment.yml incomplete

### ISSUE THREAD

**Issue by erik-buchholz** [DpTrace/PrivTrace#6]
It appears that some required packages are missing in `environment.yml`. 
In particular, `torch` and `cvxpy`. 

Could you share which versions you used? The code does not terminate for me because it hangs at the cvxpy solving in `start_end_calibrator.py`. I would like to verify if a version mismatch is the root cause of this behaviour.

Otherwise, do you have any other idea why the code could get stuck?
It hangs in the function `distribution_optimization_cvxpy2` in `start_end_calibrator.py`.

My dataset has the following properties:

**Dataset 1:**

- Number of Trajectories: 200,000
- Number of Points: 20,000,000

**Dataset 2:**
- Number of Trajectories: 55,603
- Number of Points: 11,120,600

My hardware specifications are comparable to those stated in the paper, but even though I have been running the code for 12+ hours, the code hasn't terminated.
I have not made any functional changes to the code.

**Comment by erik-buchholz** [comment]
Update:

We managed to get the code to terminate using the following packages, both installed via pip.

- torch~=2.5.1
- cvxpy~=1.6.5

The runtime for the first dataset was ~94h, and for the second one ~44h. 

**Hardware:**

- CPU: AMD EPYC 7763 (64) @ 2.450GHz
- RAM: 512 GB
- OS: Ubuntu 24.04.2 LTS x86_64

**Comment by Jichuan14** [comment]
Hello, I'm trying to run the same package, but I have issue with installing cvxpy
I use the environment.yml provided to set up the environment, but when i try to install cvxpy version 1.6.5, i have `with setup_requires=["numpy >= 1.15"]` error
I wonder how do you install all the dependencies? @erik-buchholz

**Comment by erik-buchholz** [comment]
Honestly, I ended up using an existing environment and just added cvxpy. 
This environment contains a lot of stuff you won't need for PrivTrace, but at least I got it to run with it. 
It is not compliant with the `environment.yml` in this repository, but I faced the same issues as you, so I did not want to waste my time trying to make it work.

```yml
channels:
  - defaults
dependencies:
  - pip=24.2
  - python=3.12.7
  - pip:
    - brokenaxes~=0.6.2
    - colored~=2.2.4
    - cvxpy~=1.6.5
    - deepdiff~=8.1.1
    - diffprivlib~=0.6.5
    - dtw-python~=1.5.3
    - fastdtw~=0.3.4
    - folium~=0.18.0
    - ipython~=8.30.0
    - ipywidgets~=8.1.2
    - joblib~=1.4.2
    - matplotlib~=3.9.3
    - notebook~=7.3.0rc0
    - numpy~=1.26.4
    - opacus~=1.5.2
    - pandas~=2.2.3
    - parameterized~=0.9.0
    - pillow~=10.4.0
    - pip~=24.2
    - plotly~=5.20.0
    - POT~=0.9.4
    - pydantic~=2.10.2
    - pytorch_warmup~=0.2.0
    - scikit-learn~=1.5.2
    - simple-parsing~=0.1.6
    - setuptools~=75.1.0
    - tensorboard~=2.18.0
    - torchvision~=0.20.1
    - torch~=2.5.1
    - tqdm~=4.67.1
    - tabulate~=0.9.0
    - haversine~=2.9.0
    - scipy~=1.14.1
    - typing_extensions~=4.12.2
```
